name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    # Install PlatformIO
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    # Install Project Dependencies
    - name: Install Project Dependencies
      run: platformio lib install

    # Build for Specific Environment
    - name: Build for Specific Environment
      run: platformio run --environment win_test_weather

    # Run Tests for Specific Environment
    - name: Run Tests for Specific Environment
      run: platformio test --environment win_test_weather
